#!/usr/bin/env python
"""
Generate an Ollama Modelfile embedding the Canonical System Prompt.

The Modelfile is always generated from `training.canonical_prompt` — never
hand-edited — so the deployed system prompt is byte-identical to the one
used in every training pair (ADR 0001).

Examples:

    # Baseline model (untuned Student) for the eval comparison
    PYTHONPATH=pipeline python scripts/build_modelfile.py \
        --from-ref qwen3:4b-instruct-2507 \
        --output deployment/Modelfile.baseline
    ollama create edge-slm-baseline -f deployment/Modelfile.baseline

    # Fine-tuned Student from a quantised GGUF
    PYTHONPATH=pipeline python scripts/build_modelfile.py \
        --from-ref ./edge-slm-study-notes.Q4_K_M.gguf \
        --output deployment/Modelfile.study-notes
    ollama create edge-slm-study-notes -f deployment/Modelfile.study-notes
"""

from __future__ import annotations

import argparse
from pathlib import Path

from training.canonical_prompt import CANONICAL_SYSTEM_PROMPT

MODELFILE_TEMPLATE = """\
# GENERATED by scripts/build_modelfile.py — do not edit by hand.
# The SYSTEM block is the Canonical System Prompt (ADR 0001) and must stay
# byte-identical to training.canonical_prompt.CANONICAL_SYSTEM_PROMPT.
FROM {from_ref}

PARAMETER temperature 0.2
PARAMETER num_ctx 4096
PARAMETER top_p 0.9

SYSTEM \"\"\"
{system_prompt}
\"\"\"
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--from-ref",
        required=True,
        help="Ollama FROM reference: a model tag or a GGUF file path",
    )
    parser.add_argument("--output", required=True, help="Modelfile path to write")
    args = parser.parse_args()

    content = MODELFILE_TEMPLATE.format(
        from_ref=args.from_ref, system_prompt=CANONICAL_SYSTEM_PROMPT
    )
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote {output}")
    print(f"Create the model with: ollama create <name> -f {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
